name: Release App

on:
  push:
    branches:
      - main

env:
  PB_PATH: pb
  ARTIFACT_NAME: dist


jobs:
  deploy-db:
    name: Deploy Db
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.JOTA_INFRA_APP_ID }}
          private-key: ${{ secrets.JOTA_INFRA_APP_PRIVATE_KEY }}
          owner: jota-one

      - name: Deploy db on jota infra
        run: |
          echo ${{ steps.app-token.outputs.token }} | gh auth login --with-token
          repo="${{ github.repository }}"
          commit_sha="${{ github.sha }}"
          run_external_id="$(date +%s)"
          wf_name="pb-db $repo@$commit_sha/$run_external_id"
          gh workflow run deploy-pb-db.yaml \
            --repo jota-one/infra \
            --field repo=$repo \
            --field commit-sha=$commit_sha \
            --field pb-path=${{ env.PB_PATH }} \
            --field run-external-id=$run_external_id
          sleep 5
          gh run list -R jota-one/infra -L 10 --json name,databaseId,url | jq --arg n "$wf_name" '.[] | select(.name == $n)' > .wf_run
          run_id=$(cat .wf_run | jq '.databaseId')
          run_url=$(cat .wf_run | jq '.url')
          echo "Watching workflow run $run_url"
          gh run watch $run_id --repo jota-one/infra --compact --exit-status 1

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: deploy-db
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Prepare artifact
        run: |
          mkdir _artifact && cp -r ${{ env.PB_PATH }} _artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: _artifact
          include-hidden-files: true

  deploy-app:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.JOTA_INFRA_APP_ID }}
          private-key: ${{ secrets.JOTA_INFRA_APP_PRIVATE_KEY }}
          owner: jota-one

      - name: Deploy app on jota infra
        run: |
          echo ${{ steps.app-token.outputs.token }} | gh auth login --with-token
          repo="${{ github.repository }}"
          commit_sha="${{ github.sha }}"
          run_external_id="$(date +%s)"
          wf_name="pb-app $repo@$commit_sha/$run_external_id"
          gh workflow run deploy-pb-app.yaml \
            --repo jota-one/infra \
            --field repo=$repo \
            --field commit-sha=$commit_sha \
            --field pb-path=${{ env.PB_PATH }} \
            --field build-artifact-name=${{ env.ARTIFACT_NAME }} \
            --field build-artifact-run-id=${{ github.run_id }} \
            --field run-external-id=$run_external_id
          sleep 5
          gh run list -R jota-one/infra -L 10 --json name,databaseId,url | jq --arg n "$wf_name" '.[] | select(.name == $n)' > .wf_run
          run_id=$(cat .wf_run | jq '.databaseId')
          run_url=$(cat .wf_run | jq '.url')
          echo "Watching workflow run $run_url"
          gh run watch $run_id --repo jota-one/infra --compact --exit-status 1
